-- Chèn dữ liệu cho bảng chuyen_nganh
INSERT INTO chuyen_nganh (ma_chuyen_nganh, ten_chuyen_nganh, ma_nganh, mo_ta) VALUES
('CNTT_HTTT', 'Hệ thống thông tin', 'CNTT', 'Chuyên ngành về phát triển và quản lý hệ thống thông tin'),
('CNTT_MMT', 'Mạng máy tính', 'CNTT', 'Chuyên ngành về mạng và bảo mật hệ thống'),
('CNTT_AI', 'Trí tuệ nhân tạo', 'CNTT', 'Chuyên ngành về AI, machine learning và deep learning'),
('KT_KT', 'Kế toán tài chính', 'KT', 'Chuyên ngành về kế toán tài chính và báo cáo tài chính'),
('KT_QT', 'Kế toán quản trị', 'KT', 'Chuyên ngành về kế toán quản trị và phân tích chi phí'),
('QTKD_MKT', 'Marketing', 'QTKD', 'Chuyên ngành về marketing và quảng cáo'),
('QTKD_QT', 'Quản trị', 'QTKD', 'Chuyên ngành về quản trị doanh nghiệp và chiến lược'),
('NNA_BP', 'Biên phiên dịch', 'NNA', 'Chuyên ngành về biên phiên dịch tiếng Anh'),
('NNA_GT', 'Giảng dạy', 'NNA', 'Chuyên ngành về giảng dạy tiếng Anh'),
('YK_NK', 'Nội khoa', 'YK', 'Chuyên ngành về nội khoa và điều trị bệnh'),
('YK_NG', 'Ngoại khoa', 'YK', 'Chuyên ngành về ngoại khoa và phẫu thuật'),
('DL_KS', 'Quản lý khách sạn', 'DL', 'Chuyên ngành về quản lý khách sạn và resort'),
('DL_LH', 'Lữ hành', 'DL', 'Chuyên ngành về lữ hành và tổ chức tour'),
('XD_CT', 'Công trình', 'XD', 'Chuyên ngành về thiết kế và thi công công trình'),
('XD_GT', 'Giao thông', 'XD', 'Chuyên ngành về thiết kế và thi công công trình giao thông'),
('DT_VT', 'Viễn thông', 'DT', 'Chuyên ngành về viễn thông và mạng viễn thông'),
('DT_ĐK', 'Điều khiển', 'DT', 'Chuyên ngành về điều khiển tự động và robot'),
('CK_CT', 'Chế tạo', 'CK', 'Chuyên ngành về chế tạo máy và cơ khí chính xác'),
('CK_CN', 'Công nghệ', 'CK', 'Chuyên ngành về công nghệ cơ khí và tự động hóa'),
('MT_MT', 'Môi trường', 'MT', 'Chuyên ngành về quản lý môi trường và tài nguyên'),
('MT_CN', 'Công nghệ', 'MT', 'Chuyên ngành về công nghệ môi trường và xử lý chất thải'),
('NNN_TT', 'Trồng trọt', 'NNN', 'Chuyên ngành về trồng trọt và bảo vệ thực vật'),
('NNN_CN', 'Chăn nuôi', 'NNN', 'Chuyên ngành về chăn nuôi và thú y'),
('TM_XK', 'Xuất nhập khẩu', 'TM', 'Chuyên ngành về xuất nhập khẩu và thương mại quốc tế'),
('TM_BH', 'Bán hàng', 'TM', 'Chuyên ngành về bán hàng và quản lý cửa hàng'),
('TC_NH', 'Ngân hàng', 'TC', 'Chuyên ngành về ngân hàng và tài chính ngân hàng'),
('TC_ĐT', 'Đầu tư', 'TC', 'Chuyên ngành về đầu tư và phân tích tài chính'),
('PL_DS', 'Dân sự', 'PL', 'Chuyên ngành về luật dân sự và thương mại'),
('PL_HS', 'Hình sự', 'PL', 'Chuyên ngành về luật hình sự và tố tụng hình sự'),
('GD_TC', 'Tiểu học', 'GD', 'Chuyên ngành về giáo dục tiểu học'),
('GD_TH', 'Trung học', 'GD', 'Chuyên ngành về giáo dục trung học'),
('BC_BT', 'Báo in', 'BC', 'Chuyên ngành về báo in và biên tập'),
('BC_TT', 'Truyền hình', 'BC', 'Chuyên ngành về truyền hình và phát thanh'),
('TK_ĐH', 'Đồ họa', 'TK', 'Chuyên ngành về thiết kế đồ họa và truyền thông'),
('TK_TT', 'Thời trang', 'TK', 'Chuyên ngành về thiết kế thời trang và may mặc'),
('YTC_QL', 'Quản lý', 'YTC', 'Chuyên ngành về quản lý y tế và chính sách y tế'),
('YTC_YT', 'Y tế', 'YTC', 'Chuyên ngành về y tế công cộng và phòng bệnh'),
('KHMT_AI', 'Trí tuệ nhân tạo', 'KHMT', 'Chuyên ngành về AI, machine learning và deep learning'),
('KHMT_HT', 'Hệ thống', 'KHMT', 'Chuyên ngành về hệ thống thông tin và cơ sở dữ liệu'),
('QHQT_NG', 'Ngoại giao', 'QHQT', 'Chuyên ngành về ngoại giao và quan hệ quốc tế'),
('QHQT_KT', 'Kinh tế', 'QHQT', 'Chuyên ngành về kinh tế quốc tế và thương mại quốc tế'),
('VH_VH', 'Văn hóa', 'VH', 'Chuyên ngành về văn hóa và di sản văn hóa'),
('VH_NT', 'Nghệ thuật', 'VH', 'Chuyên ngành về nghệ thuật và biểu diễn'),
('TNMT_QL', 'Quản lý', 'TNMT', 'Chuyên ngành về quản lý tài nguyên và môi trường'),
('TNMT_CN', 'Công nghệ', 'TNMT', 'Chuyên ngành về công nghệ môi trường và xử lý chất thải'),
('HTTT_HT', 'Hệ thống', 'HTTT', 'Chuyên ngành về hệ thống thông tin và cơ sở dữ liệu'),
('HTTT_CN', 'Công nghệ', 'HTTT', 'Chuyên ngành về công nghệ thông tin và truyền thông'),
('TT_MK', 'Marketing', 'TT', 'Chuyên ngành về marketing và quảng cáo'),
('TT_PR', 'PR', 'TT', 'Chuyên ngành về quan hệ công chúng và truyền thông'),
('QTNL_NS', 'Nhân sự', 'QTNL', 'Chuyên ngành về quản lý nhân sự và phát triển nguồn nhân lực'),
('QTNL_ĐT', 'Đào tạo', 'QTNL', 'Chuyên ngành về đào tạo và phát triển nhân lực'),
('KTS_KT', 'Kiến trúc', 'KTS', 'Chuyên ngành về thiết kế kiến trúc và quy hoạch đô thị'),
('KTS_NT', 'Nội thất', 'KTS', 'Chuyên ngành về thiết kế nội thất và trang trí'),
('CNSH_SH', 'Sinh học', 'CNSH', 'Chuyên ngành về sinh học và công nghệ sinh học'),
('CNSH_CN', 'Công nghệ', 'CNSH', 'Chuyên ngành về công nghệ sinh học và ứng dụng'),
('QTKS_KS', 'Khách sạn', 'QTKS', 'Chuyên ngành về quản lý khách sạn và resort'),
('QTKS_NH', 'Nhà hàng', 'QTKS', 'Chuyên ngành về quản lý nhà hàng và dịch vụ ăn uống'),
('TMDT_CN', 'Công nghệ', 'TMDT', 'Chuyên ngành về công nghệ thương mại điện tử'),
('TMDT_KD', 'Kinh doanh', 'TMDT', 'Chuyên ngành về kinh doanh trực tuyến và thương mại số'),
('QTVP_HP', 'Hành chính', 'QTVP', 'Chuyên ngành về quản lý hành chính và văn phòng'),
('QTVP_TC', 'Thư ký', 'QTVP', 'Chuyên ngành về thư ký và trợ lý hành chính');

-- Thêm cột cap_do vào bảng cau_hoi
ALTER TABLE cau_hoi ADD COLUMN cap_do TINYINT(1);

-- Cập nhật giá trị cap_do từ 1-4
UPDATE cau_hoi 
SET cap_do = FLOOR(1 + (RAND() * 4)); 